name: ci-cd

on:
  push:
    branches:
      - 'dev'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Docker Setup QEMU
      # You may pin to the exact commit or the version.
      # uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3
      uses: docker/setup-qemu-action@v3.0.0

    - name: Docker Setup Buildx
      # You may pin to the exact commit or the version.
      # uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb
      uses: docker/setup-buildx-action@v3.3.0

    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
      uses: docker/login-action@v3.1.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
      uses: docker/build-push-action@v5.3.0
      with:
        # Builder instance
        builder: ${{ steps.buildx.outputs.name }}
        # List of external cache sources for buildx (e.g., user/app:cache, type=local,src=path/to/dir)
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/e-voters-app:buildcache
        # List of cache export destinations for buildx (e.g., user/app:cache, type=local,dest=path/to/dir)
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/e-voters-app:buildcache,mode=max
        # Build's context is the set of files located in the specified PATH or URL
        context: .
        push: true
        # List of tags
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/e-voters-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          # SSH host address.
          host: ${{ secrets.SSH_HOST }}
          # SSH port number.
          port: 22
          # SSH username.
          username: ${{ secrets.SSH_USERNAME }}
          # Content of the SSH private key. For example, the raw content of ~/.ssh/id_rsa.
          key: ${{ secrets.SSH_TOKEN }}
          # Commands to be executed.
          script: |
            cd deployment-scripts/e-voters/
            docker compose pull e-voters-app
            docker compose up e-voters-app -d
            docker compose logs --tail 20 e-voters-app
